services:
  api:
    container_name: api_spring
    image: ifome/ifome:latest
    env_file:
     - ./back/.env
    ports:
      - "80:8080"
    volumes:
      - "./back/src/main/resources/static/images:/app/src/main/resources/static/images"
      - "./back/logs:/logs"
    restart: "always"
