services:
  api:
    container_name: api_spring
    image: ifome/ifome:latest
    env_file:
     - .env
    ports:
      - "80:8080"
    volumes:
      - "./src/main/resources/static/images:/app/src/main/resources/static/images"
      - "/logs:/logs"
    restart: "always"