name: Java CI with Maven

on:
  workflow_dispatch: # Executar manualmente
  push:
    branches: [ "dev" ]
    paths-ignore:
      - 'front/**'  # Ignora mudanças na pasta front

  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - 'front/**'  # Ignora mudanças na pasta front

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven and run tests
      run: | 
        cd ./back/
        mvn clean verify
      
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
  
    - name: Build Docker image
      run: |
        cd ${{ github.workspace }}/back/
        docker compose build

  deploy:
      runs-on: ubuntu-latest
      if: ${{ (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch' }}
      needs: [build, test]
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./back
          push: true
          tags: ifome/ifome:latest
          
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.APP_PATH }}
            git pull origin dev
            docker compose down
            docker compose pull
            docker compose up -d
  

